### ISSUE TITLE
Macos binaries not found for 0.9.1

### ISSUE THREAD

**Issue by LeonLenclos** [pfirsich/makelove#10]
Hi, really nice tool. Thank you for all this work !!

I found a bug trying to make my game with love 0.9.1

```
>> Building target macos
No love binaries specified for target macos
Downloading love binaries to: '/home/leon/.cache/makelove/love-binaries/0.9.1/macos'
Downloading 'https://github.com/love2d/love/releases/download/0.9.1/love-0.9.1-macos.zip'..
Could not download löve: HTTP Error 404: Not Found
If there is in fact no download on GitHub for this version, specify 'love_binaries' manually.
```

Seems like the [util.get_download_url](https://github.com/pfirsich/makelove/blob/7bbb3b0957e1672ed8cb0c5b2d76c4fe35d31bcf/makelove/util.py#L76) function does not _handle all the weird special cases_ yet... It handles 0.9.0 for mac but not 0.9.1 and 0.9.2..

**Comment by pfirsich** [comment]
Thanks a lot for reporting this bug!
I just pushed a fix and uploaded a new version to PyPI (0.0.9).
I also added a makeshift test to check that the download links work for all platform/version combinations that I think they should work for. 
I'll close this issue for now, but if you notice other issues or it still doesn't work, feel free to reopen it!
