### ISSUE TITLE
Support for love 11.4?

### ISSUE THREAD

**Issue by drhayes** [pfirsich/makelove#24]
Released January 2, 2022: https://love2d.org/forums/viewtopic.php?f=3&t=92477

> This is primarily a bugfix release plus a small number of new features and changes. The main highlights are:
> * LuaJIT 2.1 is now used in all builds where LuaJIT is bundled with LÖVE (macOS, Windows, iOS, Android, Linux AppImage).
> * LÖVE now has native Apple Silicon / arm64 support on macOS.
> * Of the many fixes, the most important one is a memory corruption / crash fix for love.graphics.line and other line-rendering APIs.

**Comment by hollunder** [comment]
Do you know what would be required? I guess https://github.com/pfirsich/love-appimages would need to be updated at least.

**Comment by flamendless** [comment]
the author has been inactive for a long time now. Does someone have a more updated fork?

**Comment by hollunder** [comment]
I wouldn't call it a long time, he has acted upon PRs a few months ago, but AFAIK Joel does not use Love himself anymore. So rather than producing a couple random forks I think it would be best to create the necessary PRs to update makelove and dependencies for Love 11.4.

It would be ideal if we could find a maintainer with enough knowledge and time that uses Love himself.

**Comment by drhayes** [comment]
> Do you know what would be required? I guess https://github.com/pfirsich/love-appimages would need to be updated at least.

I'm not so sure. I think that's only for prior versions that didn't have AppImages. This release does: https://github.com/love2d/love/releases/tag/11.4

Using it to build my game, in fact. ;)

**Comment by hollunder** [comment]
That is nice. At a glance it looks to me as if makelove can not pull those official AppImages. Still, that is probably easier to implement than to add probably superfluous AppImages to [love-appimages](https://github.com/pfirsich/love-appimages).

**Comment by MikuAuahDark** [comment]
Speaking of Linux AppImages, we (LÖVE devs) previously had issue with pfir's AppImage (love2d/love#1710) so I have to write my own AppImage packaging that compiles everything from source. I'd suggest using LÖVE-provided AppImage for 11.4, but it's possible to use the [underlying repo](https://github.com/MikuAuahDark/love-appimage-source) to build other 11.x versions.

**Comment by josh-perry** [comment]
Not totally confident I haven't broken appimages so I'll hold off on merging that until I can test it on linux.

**Comment by pfirsich** [comment]
The AppImage stuff brought quite a few changes, so if you would test this and see if it works properly, that would be great. I only tried a single game, but I messed around with it a bit.
