### ISSUE TITLE
appimage build fails on "Creating new AppImage"

### ISSUE THREAD

**Issue by RichardDally** [pfirsich/makelove#30]
Hello,

I'm running this code to package our game in an ubuntu:latest Docker image (on GitLab):
````
- apt-get update && apt-get install -y gnupg2 lsb-release
- echo "deb http://ppa.launchpad.net/bartbes/love-stable/ubuntu $(lsb_release -cs) main" | tee -a /etc/apt/sources.list
- echo "deb-src http://ppa.launchpad.net/bartbes/love-stable/ubuntu $(lsb_release -cs) main" | tee -a /etc/apt/sources.list
- apt-key adv --keyserver keyserver.ubuntu.com --recv-keys F192197F81992645
- apt-get update && apt-get install -y python3 python3-pip love wine-stable wine64 git build-essential
- python3 -m pip install makelove
- python3 -m makelove --verbose win64 appimage
````

It performs well for win64 but fails silently with linux build :

````
>> Building target win64
No love binaries specified for target win64
Downloading love binaries to: '/root/.cache/makelove/love-binaries/11.4/win64'
Downloading 'https://github.com/love2d/love/releases/download/11.4/love-11.4-win64.zip'..
Download complete
Downloading 'https://github.com/electron/rcedit/releases/download/v1.1.1/rcedit-x64.exe'..
Target win64 complete
>> Building target appimage
Downloading https://github.com/love2d/love/releases/download/11.4/love-11.4-x86_64.AppImage..
Extracting source AppImage '/tmp/tmpbcuhhggw.AppImage'..
Fusing makelove-build/appimage/squashfs-root/bin/love and makelove-build/love/stone-kingdoms.love into makelove-build/appimage/squashfs-root/bin/stone-kingdoms
Creating new AppImage..
Downloading 'https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage'..
````

I'm wondering if I'm missing something, a package to install ?
I've tested it on my Ubuntu laptop, it packaged flawlessly, but I have much more packages installed so it's hard to tell the difference.

**Comment by pfirsich** [comment]
Hello,
in what way does it fail? Is there no AppImage produced? Is it not runnable?

The appimagetool is an AppImage itself, so it requires FUSE to run. Maybe some package package is required for FUSE support? I would expect it to be installed in Desktop distributions by default, so maybe try installing the fuse package and see if that fixes it? Maybe look into other packages that need to be installed for FUSE support.

**Comment by pfirsich** [comment]
Oh! appimagetool calls into the `file` utility. I think you must install it with `sudo apt install file`.

**Comment by RichardDally** [comment]
It worked ! :+1: 
Thank you very much.
