### ISSUE TITLE
Prebuild hook fails to run command

### ISSUE THREAD

**Issue by Maiori44** [pfirsich/makelove#31]
I tried to add a prebuild hook that compiles the code to put in the build...but when running `makelove` it always says command not found.

**Comment by josh-perry** [comment]
I suspect this is the same issue as #28. What command are you trying to run?

**Comment by Maiori44** [comment]
Somehow I had not noticed issue #28
The command is `clue src -t=luajit`

**Comment by josh-perry** [comment]
Thanks for testing this, confirmed fixed
