### ISSUE TITLE
Custom license.txt

### ISSUE THREAD

**Issue by Maiori44** [pfirsich/makelove#33]
There doesn't seem to be a way to use your own license file, adding that as an option would be great

**Comment by pfirsich** [comment]
You can add additional files to copy into the archive using [[archive_files]](https://github.com/pfirsich/makelove/blob/master/makelove_full.toml#L55). The example includes a directory of licenses and a readme file. You can just treat it like another readme.

**Comment by Maiori44** [comment]
Doesn't that work only on window builds?

**Comment by pfirsich** [comment]
There is [windows.archive_files], which is a special override for windows (in case you want different files on a specific platform). But [archive_files] is used for every platform.

**Comment by Maiori44** [comment]
I checked the inside of the macos build and it does not use the custom license.txt.
Even in the makelove_full.toml in the description for [archive files] it says
> This specifies the files to be included in the zip archives generated **for windows builds.**

**Comment by pfirsich** [comment]
Damn. Super sorry! You are absolutely right. The .AppImage is not supposed to be shared in an archive https://docs.appimage.org/packaging-guide/distribution.html?highlight=zip#do-not-put-appimages-into-other-archives, so there really isn't a way to do this well. Let me know if you have an idea for a solution on this. And I really don't know anything about Mac.

**Comment by Maiori44** [comment]
It's okay dw lol
a possible solution I can think of could be having the license have its own variable in the toml, and when that variable is present it overwrites the original license.txt that it was going to use (the macos build does have a license file inside it, which seems to be the original love2d one, so it must be taken from somewhere..so that somewhere can be overwritten)

but I don't really know how makelove works internally so this may not be actually possible

**Comment by pfirsich** [comment]
Closed by #35, I think!
