### ISSUE TITLE
Wrong Check on Official LOVE AppImage

### ISSUE THREAD

**Issue by MikuAuahDark** [pfirsich/makelove#37]
https://github.com/pfirsich/makelove/blob/84af8c1b0a9f13d737366856e9dbdb9057ed4ab8/makelove/linux.py#L24-L27

This won't catch LOVE 12.0, 12.1, 12.2, 12.3, 13.0, and so on.

Suggested change:
```py
if (parsed_version[0], parsed_version[1]) >= (11, 4):
    return download_official_appimage(version) 
```

**Comment by pfirsich** [comment]
I don't know how you found that, but thank you for the early notice! I'll double check why it is that way and then fix it. I don't think it's worth it to release a new version for it. Would it be okay to give a day's notice before releasing love 12 or something?

**Comment by MikuAuahDark** [comment]
A new commit is not necessarily a new release.

**Comment by pfirsich** [comment]
That was kind of my point. It's fixed on master now, but I don't think I want to release for this. I am pretty sure most people just install makelove via pip, so it should be updated there if people are supposed to use it. Do you think you could notify me a day before releasing love 12, so I can release then?

**Comment by MikuAuahDark** [comment]
Ah. Yes sure thing.
